### ISSUE TITLE
Make gem available over rubygems.org

### ISSUE THREAD

**Issue by lachlanjc** [theseoafs/shittydb#16]
Hey @theseoafs! It doesn't look like the gem is available over Rubygems.org yet... :cry: 

http://guides.rubygems.org/publishing/

**Comment by rickystewart** [comment]
Seems complicated

**Comment by lachlanjc** [comment]
@theseoafs It's not hard at all — but no one can use the gem if it's not published, and Rubygems is by far the most popular hosting platform. Did you want help?
