### ISSUE TITLE
Python no longer cross-platform

### ISSUE THREAD

**Issue by haselkern** [theseoafs/shittydb#25]
It seems like someone <sub><sup>(_cough_ @SAMdroid-apps)</sup></sub> had fun implementing linux only commands. Unfortunately that removes a lot of the scalability and flexibility.

**Comment by rickystewart** [comment]
Mhm, I see.  Unfortunately we are too webscale to have automated unit tests so unfortunately this could not have been foreseen.

**Comment by samdroid-apps** [comment]
Hum, is there a library to fix this?  Like jQuery maybe?

**Comment by haselkern** [comment]
I did find [pyquery](https://pypi.python.org/pypi/pyquery) but in this case the problem was solvable without it. See my new pull request.
