### ISSUE TITLE
Not shitty enough!

### ISSUE THREAD

**Issue by iTwenty** [theseoafs/shittydb#4]
When I first saw the project title, I felt elated! I thought I had finally found a DB that dares to go beyond boring CRUD operations and performs actual shitty things. My expectations were set very high.  I was expecting it to do things like:
- Delete random system files
- Shut down my laptop randomly
- Consume full CPU and RAM for no reason
- Summon Cthulhu to obliterate the known universe

But the current version doesn't do any of this :( Maybe you should consider renaming it to something like "not-so-shitty-db" or add the requested features?

**Comment by outadoc** [comment]
I think ShittyDB performs way too well, too. Maybe add a few useless for loops for added shittiness?

**Comment by rickystewart** [comment]
Hi iTwenty,

Unfortunately shittyDB is a work in progress and we only have so much venture capital.  Therefore it is unfortunately impossible for us to fulfill every feature request.  

If you have some free time, I encourage you to ~~do our work for us~~ submit a pull request with this functionality.  

As for summoning Cthulu: Python is unfortunately not my native language so I don't know how to do that.  Is it just:

```
import cthulu
cthulu.summon()
```

?

**Comment by AdamHess** [comment]
Has shitty DB considered becoming a part of the SHIT stack.  SHITTYDb Headfuck (variant of brain fuck)  Indigo go funded and Theoretically  shouldn't work

**Comment by rickystewart** [comment]
If you can implement ShittyDB in Brainfuck I will send you two dollars

**Comment by vance** [comment]
I tried to import this 239,184,976 line CSV and the RAM kept ballooning, so I had to upgrade my EC2 instance to 48GB. One I got it to import I got this error: 

Action: Either: o) rename the given identifier, o) qualify any references to the identifier with the containing scope's name, or o) make sure the intended resolution occurs if using the identifier in ShitDB scope. 

So I clicked option 3 and 'ok' for every row in the table. I'm so old now that my testicles dip in the toilet water when I poop.

**Comment by vance** [comment]
Whew, sweet it finally works, so now I can index SOLR with he new data... Or so I thought. Now the shitty slave is locked and the shitty shards keep falling out of sync. You guys need to fix the replicator or I'm switching to a new architecture.

**Comment by rodricios** [comment]
Came to confirm that you can store elasticsearch into shittyDB. This is truly a big pile of awesome shit.

**Comment by rickystewart** [comment]
Hi @vance.  What does RAM mean?

**Comment by iTwenty** [comment]
@theseoafs It's software you download to make your computer faster. Download from here -> http://downloadmoreram.com
